# -*- coding: utf-8 -*-
"""Base de dados

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16j-N5YeSsw3JLfXRDxH_Q10I2TDBiuXD

#Relatório de análise I
"""

import pandas as pd

dados = pd.read_csv('aluguel.csv', sep = ';')
dados.head()

"""#Informações gerais sobre a base de dados"""

dados.dtypes

tipos_de_dados = pd.DataFrame(dados.dtypes, columns = ['Tipos de dados'])
tipos_de_dados.columns.name = 'Variáveis'
tipos_de_dados

#dados.shape
#dados.shape[0]
#dados.shape[1]
print("A base de dados apresenta {} linhas(imóveis) e {} colunas(variáveis)".format(dados.shape[0], dados.shape[1]))

"""#Relatório de análise II

##Tipos de imóveis
"""

tipos_de_imoveis = dados['Tipo'] #Selecionando uma coluna da tabela
type(tipos_de_imoveis)  #series
tipos_de_imoveis.drop_duplicates(inplace = True) #Eliminando as linhas repetidas, e atribuindo ja
tipos_de_imoveis = pd.DataFrame(tipos_de_imoveis) #Criando um DataFrame
tipos_de_imoveis.columns.name = 'ID' #Mudando o nome do index
tipos_de_imoveis

len(tipos_de_imoveis.index) #Lendo quantos valores tem no index(ID)

for i in range(len(tipos_de_imoveis.index)): #Printando o range do tamanho do index(ID)
  print(i)

tipos_de_imoveis.index = range(1, len(tipos_de_imoveis.index)+1)  #Colocando o valor do range no lugar do index(ID), começando de 1 e indo até len + 1
tipos_de_imoveis

"""#Series"""

data = [1, 2, 3, 4, 5] # Criando uma list
s = pd.Series(data)    # Passando para uma serie
s

index = ['Linha ' + str(i+1) for i in range(5)]  # Alterando o index da serie
s = pd.Series(data, index)
s

s2 = s + 2       #Operações com series
s2

s3 = s + s2
s3

"""#Data Frame"""

dados = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

dados

df1 = pd.DataFrame(data = dados)   #Criando um data frame e passando os dados
df1

index = ["Linha " + str(i+1) for i in range(3)]         #Criando o index e a coluna para o df
columns = ["Coluna " + str(i+1) for i in range(3)]

df1 = pd.DataFrame(data = dados, index = index, columns = columns)  #Passando o index e coluna para o df
df1

df1[df1 > 0] = 'A'     #Elementos maiores que 0, troca para A
df1

df2 = pd.DataFrame(data = dados, index = index, columns = columns) #Criando df igual
df3 = pd.DataFrame(data = dados, index = index, columns = columns)

df2[df2 > 0] = 'B'    #Trocando tudo por B
df3[df3 > 0] = 'C'    #Trocando tudo por C

df4 = pd.concat([df1, df2, df3])      #Concatenando os dfs
df4

df4 = pd.concat([df1, df2, df3], axis = 1)  #Concatenando por linha
df4