# -*- coding: utf-8 -*-
"""Criando Agrupamentos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15n7nLe15HvEWkeKy48QTejM-RLRlwB7E

#Relatório de análise VII

##Criando agrupamentos
"""

import pandas as pd

dados = pd.read_csv('aluguel_residencial3.csv', sep = ';')
dados.head()

dados['Valor'].mean()

bairros = ['Barra da Tijuca', 'Copacapana', 'Ipanema', 'Leblon', 'Botafogo', 'Flamengo', 'Tijuca']
selecao = dados['Bairro'].isin(bairros)   #Seleciona apenas os bairros da lista
dados = dados[selecao]

dados['Bairro'].drop_duplicates()  #Elimina os duplicados para ter certeza que deu certo o drop

grupo_bairro = dados.groupby('Bairro')
type(grupo_bairro)

grupo_bairro.groups

for bairro, data in grupo_bairro:
  print('{} -> {}'.format(bairro, data.Valor.mean()))

grupo_bairro[['Valor', 'Condominio']].mean().round(2)

"""#Estatísticas descritivas"""

grupo_bairro['Valor'].describe().round(2)

grupo_bairro['Valor'].aggregate(['min', 'max']).rename(columns = {'min': 'Mínimo', 'max': 'Máximo'})

import matplotlib.pyplot as plt
plt.rc('figure', figsize = (20, 10))  #Configurando matplot

fig = grupo_bairro['Valor'].mean().plot.bar(color = 'blue')  #Plotando
fig.set_ylabel('Valor do aluguel')  #Mudando o nome do eixo y
fig.set_title('Valor médio do aluguel', {'fontsize': 22})  #Mudando o titulo

fig = grupo_bairro['Condominio'].mean().plot.bar(color = 'blue')
fig.set_ylabel('Valor do condominio')
fig.set_title('Valor médio do condomio', {'fontsize': 22})

"""#Criando faixas de valor"""

dados
#Contar quantos imoveis tem de 1 a 2 quartos, de 3 a 4, de 5 a 6, 7 ou mais
classes = [0, 2, 4, 6, 100]

quartos = pd.cut(dados['Quartos'], classes)
quartos

pd.value_counts(quartos)

labels = ['1 e 2 quartos', '3 e 4 quartos', '5 e 6 quartos', '7 ou mais quartos']

quartos = pd.cut(dados['Quartos'], classes, labels = labels)
pd.value_counts(quartos)

quartos = pd.cut(dados['Quartos'], classes, labels = labels, include_lowest = True)
pd.value_counts(quartos)