# -*- coding: utf-8 -*-
"""Criando novas variaveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IlATsbc8IattG-_s_ldDUoIEhVCNSdH7

#Relatório de análise VI

##Criando novas variáveis
"""

import pandas as pd

dados = pd.read_csv('aluguel_residencial2.csv', sep = ';')
dados.head()

dados['Valor Bruto'] = dados['Valor'] + dados['Condominio'] + dados['IPTU'] #Somando os valores de 3 colunas e adicionando a uma nova
dados.head()

dados['Valor m2'] = dados['Valor'] / dados['Area']  #Dividindo valores de colunas
dados['Valor m2'] = dados['Valor m2'].round(2)  #Utilizando 2 casas
dados.head()

dados['Valor bruto m2'] = (dados['Valor Bruto'] / dados['Area']).round(2)  
dados.head()

casa = ['Casa', 'Casa de Condomínio', 'Casa de Vila']
dados['Tipo Agregado'] = dados['Tipo'].apply(lambda x: 'Casa' if x in casa else 'Apartamento')  #Separando em casa ou apartamento

dados

"""#Excluindo variáveis"""

dados_aux = pd.DataFrame(dados[['Tipo Agregado', 'Valor m2', 'Valor Bruto', 'Valor bruto m2']])
dados_aux

del dados_aux['Valor Bruto']  #Uma forma de excluir variavel
dados_aux

dados_aux.pop('Valor bruto m2')  #Outra forma
dados_aux

dados.drop(['Valor Bruto', 'Valor bruto m2'], axis = 1, inplace = True)  #Eliminando com drop
dados

dados.Tipo.value_counts()  #Contador