# -*- coding: utf-8 -*-
"""Tratamento de dados faltantes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fTSL_EMLPsxyWkPIi8TmvZxyLNBmJfu3

#Relatório de análise V

##Tratamento de dados faltantes
"""

import pandas as pd

dados = pd.read_csv('aluguel_residencial.csv', sep = ';')
dados

dados.isnull()  #Mostra os valores nulos como true

dados.notnull()  #Mostra os valores nao nulos como true

dados.info()

dados['Valor'].isnull()  #Cria uma series

dados[dados['Valor'].isnull()]  #Mostra os imóveis com valor Nan

A  = dados.shape[0]
dados.dropna(subset = ['Valor'], inplace = True)  #Dropna para eliminar os valor NaN da tabela
B = dados.shape[0]
A - B

dados[dados['Valor'].isnull()]  #Agora está vazio

"""#Tratamento de Dados Faltantes(Continuação)"""

dados[dados['Condominio'].isnull()].shape[0]

selecao = (dados['Tipo'] == 'Apartamento') & (dados['Condominio'].isnull())

A = dados.shape[0]
dados = dados[~selecao]  #Eliminando os apartamentos com condiminio Nan utilizando o ~
B = dados.shape[0]
A - B

dados[dados['Condominio'].isnull()].shape[0]

dados = dados.fillna({'Condominio' : 0, 'IPTU': 0})  #Trocou os valores Nan por 0

dados[dados['Condominio'].isnull()].shape[0]

dados[dados['IPTU'].isnull()].shape[0]

dados.info()  #Informaçoes nao nulas

dados.to_csv('aluguel_residencial.csv', sep = ';', index = False)

"""#Métodos de interpolação"""

data = [0.5, None, None, 0.52, 0.54, None, None, 0.59, 0.6, None, 0.7]
s = pd.Series(data)

s

s.fillna(0)  #Troca Nan por 0

s.fillna(method = 'ffill') #Troca pelo valor que vem antes dele

s.fillna(method = 'bfill') #Troca pelo valor que vem depois

s.fillna(method = 'ffill', limit = 1) #Troca pelo valor que vem antes dele mas com um limite de uma casa